# apps/web/Dockerfile.dev
FROM node:20-alpine 

WORKDIR /app

# Install pnpm (required for running pnpm install)
RUN npm install -g pnpm

# Install dependencies for the whole workspace
COPY pnpm-workspace.yaml .
COPY pnpm-lock.yaml .
COPY package.json .
COPY ./apps/web/package.json ./apps/web/package.json

RUN pnpm install --frozen-lockfile

# Copy the entire source code
COPY . .

# Vite default dev port
EXPOSE 5173

# CMD to run the development server via pnpm workspace filtering
CMD ["pnpm", "--filter", "web", "dev"]
